config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :masks, :patterns
  resources :orders do 
    member do
      post :deliver
    end
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mask.rb
class Mask < ApplicationRecord
  belongs_to :order
  before_create :default_values
  validates :pattern, presence: true

  def default_values
    self.cut = false
    self.sewn = false
    self.band = false
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :masks, dependent: :destroy
  validates :name, presence: true
end

app/models/pattern.rb
class Pattern < ApplicationRecord
  validates :name, presence: true
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/style.rb
class Style < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @orders = Order.order("id DESC").where(delivered: nil)
  end

end

app/controllers/masks_controller.rb
class MasksController < ApplicationController

  def new
    helpers.set_current_order(params[:order])
  end

  def create
    @order = Order.find(helpers.current_order)
    @mask = @order.masks.build(mask_params)
    if @mask.save
      redirect_to root_url(update_id: @order.id)
    else
      render "new"
    end
  end

  def edit
    @mask = Mask.find(params[:id])
  end

  def update
    @mask = Mask.find(params[:id])
    if @mask.update(mask_params)
      redirect_to root_url(update_id: @order.id)
    else
      render "edit"
    end
  end

  def destroy
    @mask = Mask.find(params[:id]).destroy
    redirect_to root_url
  end

  private

    def mask_params
      params.require(:mask).permit(:size, :style, :pattern, :cut, :sewn, :band)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.order("id DESC").where(delivered: true)
  end

  def new
  end

  def show
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to root_url(update_id: @order.id)
    else
      render "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @order.find(params[:id]).destroy
    redirect_to root_url
  end

  def deliver
    @order = Order.find(params[:id])
    @order.update(delivered: true)
    redirect_to root_url
  end

  private

    def order_params
      params.require(:order).permit(:name)
    end

end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController

  def index
    @patterns = Pattern.all
  end

  def new
  end

  def create
    @pattern = Pattern.new(pattern_params)
    if @pattern.save
      redirect_to patterns_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def pattern_params
      params.require(:pattern).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/masks_helper.rb
module MasksHelper

  def set_current_order(order)
    session[:order_id] = order
  end

  def current_order
    session[:order_id]
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasqueOrders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1 class="float-left">Orders</h1>

<div class="orders-patterns-button float-right">
  <%= link_to "Patterns", patterns_path, class: "btn btn-primary" %>
</div>

<%# -- create a new order/insert view on click -- %>
<%= button_to "Create Order", new_order_path, method: :get, remote: true, class: "btn btn-primary form-control mb-3" %>

<div class="new-order"></div>
<%# -- end new order-- %>

<div class="orders mb-3">
  <% @orders.each do |order| %> <%# -- iterate undelivered orders -- %>
    <div class="order">
      <div class="order-<%= order.id %>">
        <%= link_to order.name, order, remote: true, id: "order-#{order.id}" %>
      </div>
      <div class="masks-<%= order.id %>">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">size</th>
              <th scope="col">style</th>
              <th scope="col">pattern</th>
              <th scope="col">cut</th>
              <th scope="col">sewn</th>
              <th scope="col">band</th>
              <th scope="col">edit</th>
              <th scope="col">delete</th>
            </tr>
          </thead>
          <tbody>
            <% order.masks.each do |mask| %>
              <tr> <%# -- Begin mask iteration of order -- %>
                <td scope="row"><%= mask.size %></td>
                <td><%= mask.style %></td>
                <td><%= mask.pattern %></td>
                <%= fields_for mask, :cut do |f| %>
                  <td><%= f.check_box :cut, disabled: true %></td>
                <% end %>
                <%= fields_for mask, :sewn do |f| %>
                  <td><%= f.check_box :sewn, disabled: true %></td>
                <% end %>
                <%= fields_for mask, :band do |f| %>
                  <td><%= f.check_box :band, disabled: true %></td>
                <% end %>
                <td><%= button_to "/", edit_mask_path(mask), method: :get, class: "btn btn-warning"%></td>
                <td><%= button_to "-", mask_path(mask), method: :delete, data: { confirm: "You really want to delete the mask?" }, class: "btn btn-danger" %></td>
              </tr> <%# -- end mask iteration -- %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="order-<%= order.id %>-options">
        <%# -- create a new mask/insert view on click -- %>
        <div class="new-mask-<%= order.id %>"></div>
        <%= link_to "Add mask to #{order.name}", new_mask_path( order: order.id ), remote: true, class: "btn btn-success form-control mb-3" %>
        <%# -- end new mask -- %>
        <%# -- deliver order -- %>
        <%= link_to 'Deliver Order', deliver_order_path(order), method: :post, class: "btn btn-info form-control" %>
      </div>
    </div>
  <% end %>
</div>
<%= link_to 'Completed Orders', orders_path %>

<% if params[:update_id] %>
  <script>
      $(".order-<%= params[:update_id] %>").get(0).scrollIntoView();
      $(".order-<%= params[:update_id] %>-options").toggleClass("active");
      $(".masks-<%= params[:update_id] %>").toggleClass("active");
  </script>
<% end %>

app/views/masks/_new.html.erb
<%= form_with model: Mask.new, class: "form-group" do |f| %>
  <%= f.label :size, class: "sr-only" %>
  <%= f.select :size, Size.all.collect{|s| s.name }, {}, class: "form form-control mb-3" %>
  <%= f.label :style, class: "sr-only" %>
  <%= f.select :style, Style.all.collect{|s| s.name }, {}, class: "form form-control mb-3" %>
  <%= f.label :pattern, class: "sr-only" %>
  <%= f.select :pattern, Pattern.all.collect{|s| s.name }, {}, class: "form form-control mb-3" %>
  <%= f.submit "Submit", class: "btn btn-success form-control" %>
<% end %>

app/views/masks/edit.html.erb
<h1><%= @mask.order.name %></h1>
<%= form_with model: @mask, class: "form-group" do |f| %>
  <%# f.hidden_field :order, value: params[:order] %>
  <div class="input-group mb-3">
    <%= f.label :size, class: "sr-only" %>
    <%= f.select :size, Size.all.collect{|s| s.name }, {}, class: "form form-control" %>
  </div>
  <div class="input-group mb-3">
    <%= f.label :style, class: "sr-only" %>
    <%= f.select :style, Style.all.collect{|s| s.name }, {}, class: "form form-control" %>
  </div>
  <div class="input-group mb-3">
    <%= f.label :pattern, class: "sr-only" %>
    <%= f.select :pattern, Pattern.all.collect{|s| s.name }, {}, class: "form form-control" %>
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <div class="input-group-text">
        <%= f.check_box :cut, {}, :true, :false %>
      </div>
    </div>
    <%= f.label :cut, class: "form-control" %>
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <div class="input-group-text">
        <%= f.check_box :sewn, {}, :true, :false %>
      </div>
    </div>
    <%= f.label :sewn, class: "form-control" %>
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <div class="input-group-text">
        <%= f.check_box :band, {}, :true, :false %>
      </div>
    </div>
    <%= f.label :band, class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-success form-control" %>
<% end %>

app/views/masks/new.js.erb
$(".new-mask-<%= params[:order] %>").html("<%= j render 'new' %>")

app/views/orders/_new.html.erb
<%= form_with model: Order.new, class: "form-group" do |f| %>
  <%= f.label :name, class: "mt-3" %>
  <%= f.text_field :name, class: "form form-control mb-3" %>
  <%= f.submit "Submit", class: "btn btn-success form-control" %>
<% end %>

app/views/orders/index.html.erb
<h1>Orders</h1>
<%= link_to 'Back', root_url %>
<div class="orders">
  <% @orders.each do |order| %> <%# -- iterate undelivered orders -- %>
    <div class="order">
      <div class="order-<%= order.id %>">
        <%= link_to order.name, order, remote: true, id: "order-#{order.id}" %>
      </div>
      <div class="masks-<%= order.id %>">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">size</th>
              <th scope="col">style</th>
              <th scope="col">pattern</th>
            </tr>
          </thead>
          <tbody>
            <% order.masks.each do |mask| %>
              <tr> <%# -- Begin mask iteration of order -- %>
                <td scope="row"><%= mask.size %></td>
                <td><%= mask.style %></td>
                <td><%= mask.pattern %></td>
              </tr> <%# -- end mask iteration -- %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/new.js.erb
$('.new-order').html("<%= j render 'new' %>")

app/views/orders/show.js.erb
$(".order-<%= params[:id] %>-options").toggleClass("active")
$(".masks-<%= params[:id] %>").toggleClass("active")

app/views/patterns/_new.html.erb
<%= form_with model: Pattern.new, class: "form-group" do |f| %>
  <%= f.label :name, class: "mt-3" %>
  <%= f.text_field :name, class: "form form-control mb-3" %>
  <%= f.submit "Submit", class: "btn btn-success form-control" %>
<% end %>

app/views/patterns/index.html.erb
<h1 class="float-left">Patterns</h1>
<div class="orders-patterns-button float-right">
  <%= link_to 'Orders', root_url, class: "btn btn-primary" %>
</div>
<%= link_to 'Create Pattern', new_pattern_path, method: :get, remote: true, class: "btn btn-primary form-control mb-3" %>
<div class="new-pattern"></div>
<table class="table table-striped">
  <tbody>
    <% @patterns.each do |pattern| %>
      <tr class="align-items-center">
        <td class="cell" style="line-height: 36px;"><%= pattern.name %></td>
        <td class="cell"><%= link_to 'edit', edit_pattern_path(pattern), class: "btn btn-warning" %></td>
        <td class="cell"><%= link_to 'delete', pattern_path(pattern), class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/patterns/new.js.erb
$('.new-pattern').html("<%= j render 'new' %>")